"""Table 1: participants and recordings by study and group.

Reads demographics.txt and the record files in data/raw/gaitpdb and writes
results/table1_participants.csv and results/table1_participants.md.

    python scripts/make_table1.py [--data data/raw/gaitpdb]
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))
from gaitpdb import build_manifest, find_data_dir, load_demographics  # noqa: E402

STUDY_LABEL = {
    "Ga": "Ga: dual task",
    "Ju": "Ju: auditory cueing",
    "Si": "Si: treadmill study",
}


def fmt_mean_sd(x: pd.Series) -> str:
    x = x.dropna()
    return f"{x.mean():.1f} ± {x.std(ddof=1):.1f}" if len(x) > 1 else "n/a"


def fmt_median_range(x: pd.Series) -> str:
    x = x.dropna()
    return f"{x.median():g} ({x.min():g}–{x.max():g})" if len(x) else "n/a"


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--data", default="data/raw/gaitpdb")
    ap.add_argument("--out", default="results")
    args = ap.parse_args()

    data_dir = find_data_dir(args.data)
    demo = load_demographics(data_dir)
    manifest = build_manifest(data_dir)
    out = Path(args.out)
    out.mkdir(parents=True, exist_ok=True)

    rows = []
    for study in ("Ga", "Ju", "Si"):
        for group in ("PD", "Control"):
            d = demo[(demo["Study"] == study) & (demo["group"] == group)]
            m = manifest[(manifest["study"] == study) & (manifest["group"] == group)]
            per_participant = m.groupby("participant").size()
            rows.append(
                {
                    "Study": STUDY_LABEL[study],
                    "Group": group,
                    "Participants (demographics)": len(d),
                    "Participants with recordings": m["participant"].nunique(),
                    "Recordings": len(m),
                    "Recordings per participant": fmt_median_range(per_participant),
                    "Recording length, s": fmt_median_range(m["duration_s"].round(0)),
                    "Age, years": fmt_mean_sd(d["Age"]),
                    "Women, n": int((d["sex"] == "F").sum()),
                    "Hoehn and Yahr": fmt_median_range(d["HoehnYahr"])
                    if group == "PD"
                    else "",
                    "UPDRS motor": fmt_mean_sd(d["UPDRSM"]) if group == "PD" else "",
                }
            )
    # totals
    for group in ("PD", "Control"):
        d = demo[demo["group"] == group]
        m = manifest[manifest["group"] == group]
        per_participant = m.groupby("participant").size()
        rows.append(
            {
                "Study": "All",
                "Group": group,
                "Participants (demographics)": len(d),
                "Participants with recordings": m["participant"].nunique(),
                "Recordings": len(m),
                "Recordings per participant": fmt_median_range(per_participant),
                "Recording length, s": fmt_median_range(m["duration_s"].round(0)),
                "Age, years": fmt_mean_sd(d["Age"]),
                "Women, n": int((d["sex"] == "F").sum()),
                "Hoehn and Yahr": fmt_median_range(d["HoehnYahr"])
                if group == "PD"
                else "",
                "UPDRS motor": fmt_mean_sd(d["UPDRSM"]) if group == "PD" else "",
            }
        )
    table = pd.DataFrame(rows)
    table.to_csv(out / "table1_participants.csv", index=False)
    with open(out / "table1_participants.md", "w", encoding="utf-8") as f:
        f.write(
            "Table 1. Participants and recordings in the PhysioNet Gait in Parkinson's Disease "
            "database by sub-study and group. Age and UPDRS motor score are mean ± SD; recordings per "
            "participant, recording length and Hoehn and Yahr stage are median (range). Generated by "
            "scripts/make_table1.py from demographics.txt and the record files.\n\n"
        )
        f.write(table.to_markdown(index=False))
        f.write("\n")
    # participants in demographics without a recording, and vice versa
    missing = sorted(set(demo["ID"]) - set(manifest["participant"]))
    extra = sorted(set(manifest["participant"]) - set(demo["ID"]))
    notes = [
        f"Participants in demographics.txt without a record file: {missing or 'none'}",
        f"Record files without a demographics row: {extra or 'none'}",
        f"Total record files: {len(manifest)}; total participants with recordings: {manifest['participant'].nunique()}",
        f"Ages missing: {int(demo['Age'].isna().sum())}; Hoehn and Yahr missing among PD: {int(demo.loc[demo['group'] == 'PD', 'HoehnYahr'].isna().sum())}",
    ]
    (out / "table1_notes.txt").write_text("\n".join(notes) + "\n", encoding="utf-8")
    print(table.to_string(index=False))
    print("\n".join(notes))


if __name__ == "__main__":
    main()
